[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.8"
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--prefer-offline --no-audit"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Environment variables needed (set these in Netlify UI):
# NEXTAUTH_URL=https://your-app.netlify.app
# NEXTAUTH_SECRET=your-random-secret
# DATABASE_URL=your-postgresql-url
# SUPABASE_URL=your-supabase-url
# SUPABASE_ANON_KEY=your-supabase-anon-key
# SUPABASE_SERVICE_ROLE_KEY=your-supabase-service-role-key
# OPENAI_API_KEY=your-openai-key
# STRIPE_SECRET_KEY=your-stripe-secret
# STRIPE_WEBHOOK_SECRET=your-stripe-webhook-secret